sudo: required # need super user permissions
services:
  - docker #installs a copy of docker into the running container

before_install: #gets executed before we run the tests (or deployment)
  - docker build -t samindiw/docker-react -f Dockerfile.dev .

script: #commands to actually do what we want it to do
  - docker run -e CI=true samindi/docker-react npm run test