version: '3'

services:
  web:
    build: 
      context: . #where we want all the files and folders for this image to be pulled from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app #we want to map the current directory outside of the container to the app folder inside the container.

    